# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Daniel Knopp, MPP
tagline:          'Senior Research Analyst'
description:      'Working at the intersection of technology and policy'
url:              dknsc.github.io/dknopp.github.io
baseurl:          dknopp.github.io

author:
  name:           'Daniel Knopp'
  url:            danielknopp.com

paginate:         1

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

defaults:
  - scope:
      path: about.md
    values:
      menu: true
      order: 1
  - scope:
      path: projects.md
    values:
      menu: true
      order: 2
  - scope:
      path: cv.md
    values:
      menu: true
      order: 3
