# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Daniel Knopp, MPP
tagline:          'Senior Research Analyst'
description:      'Working at the intersection of technology and policy'
url:              dknsc.github.io/dknopp.github.io
baseurl:          /

author:
  name:           'Daniel Knopp'
  url:            danielknopp.com

paginate:         1

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

menu:
  - title: Resume
    url:   /resume/
  - title: About
    url:   /about/
  - title: Projects
    url:   /projects/

